/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewsList: typeof import('./src/components/NewsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopToolbar: typeof import('./src/components/TopToolbar.vue')['default']
  }
}
