/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    Confirm: typeof import('./src/components/recharge/confirm.vue')['default']
    copy: typeof import('./src/components/withdrawConfirm copy/index.vue')['default']
    CountDown: typeof import('./src/components/countDown/index.vue')['default']
    DepositConfirm: typeof import('./src/components/depositConfirm/index.vue')['default']
    Recharge: typeof import('./src/components/recharge/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rules: typeof import('./src/components/rules/index.vue')['default']
    TopToolbar: typeof import('./src/components/TopToolbar.vue')['default']
    WithdrawConfirm: typeof import('./src/components/withdrawConfirm/index.vue')['default']
  }
}
